server:
  port: 8081

spring:
  application:
    name: shop-eureka

# 注册服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    # 把自己注册到eureka上
    register-with-eureka: true
    # 是否从eureka拉取注册信息
    fetch-registry: true

