server:
  port: 8888



jwt:
  config:
    key: itcast
    ttl: 3600000


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jdbc?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456