server:
  port: 8082

spring:
  application:
    name: consumer-server

# 注册服务中心
eureka:
#  instance:
#    #主机ip
#    hostname: localhost
  client:
    # 表示是否将自己注册到Eureka Servier上, 默认为false
    register-with-eureka: true
    # 表示是否从Eureka Server上获取注册信息, 默认为true
    fetch-registry: true
    # 拉取服务列表的时间周期
#    registry-fetch-interval-seconds: 30000
    # 注册地址
    service-url:
      defaultZone: http://localhost:8083/eureka/,http://localhost:8084/eureka/


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
