package com.atguigu.bean;

import java.util.Date;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.name
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.course
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    private String course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.address
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.birth
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    private Date birth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.name
     *
     * @return the value of teacher.name
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.name
     *
     * @param name the value for teacher.name
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.course
     *
     * @return the value of teacher.course
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    public String getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.course
     *
     * @param course the value for teacher.course
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    public void setCourse(String course) {
        this.course = course == null ? null : course.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.address
     *
     * @return the value of teacher.address
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.address
     *
     * @param address the value for teacher.address
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.birth
     *
     * @return the value of teacher.birth
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.birth
     *
     * @param birth the value for teacher.birth
     *
     * @mbg.generated Thu Jul 18 18:14:21 CST 2019
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }
}