spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mp?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#  configuration:
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl